### PR TITLE
JavaFX Renderer

### PR DESCRIPTION
**Pull request by dmarcuse**
JavaFX is much faster and more flexible than Swing/AWT, so I'm writing a JavaFX rendering plugin. It doesn't add any extra dependencies, since recent Java versions include JavaFX.

- [x] Basic rendering
- [x] Key input
- [x] Mouse input
- [x] Special combos (terminate/shutdown/reboot)
- [x] Cursor blink
- [x] Window decoration/style
- [x] Extras (drag and drop, whatever else we can think of)

### CODE REVIEW

**Comment by Lignum** [comment]
> since recent Java versions include JavaFX

How recent? We're targeting Java 8 in `build.gradle`. I can't build it because I have a million errors like this:
```
/home/lig/projects/CCEmuX/src/main/java/net/clgd/ccemux/rendering/javafx/ConfigBindings.java:7: error: package javafx.beans does not exist
import javafx.beans.InvalidationListener;
                   ^
/home/lig/projects/CCEmuX/src/main/java/net/clgd/ccemux/rendering/javafx/ConfigBindings.java:8: error: package javafx.beans.property does not exist
import javafx.beans.property.ObjectProperty;
                            ^
/home/lig/projects/CCEmuX/src/main/java/net/clgd/ccemux/rendering/javafx/ConfigBindings.java:9: error: package javafx.beans.property does not exist
import javafx.beans.property.Property;
                            ^
/home/lig/projects/CCEmuX/src/main/java/net/clgd/ccemux/rendering/javafx/ConfigBindings.java:10: error: package javafx.beans.value does not exist
import javafx.beans.value.ChangeListener;
                         ^
/home/lig/projects/CCEmuX/src/main/java/net/clgd/ccemux/rendering/javafx/ConfigBindings.java:11: error: package javafx.beans.value does not exist
import javafx.beans.value.ObservableValue;
```

I have OpenJDK 9 installed, and it should be set up correctly since `java -version` outputs this:
```
openjdk version "9"
OpenJDK Runtime Environment (build 9+181)
OpenJDK 64-Bit Server VM (build 9+181, mixed mode)
```

So I'm guessing Gradle is using a version of Java which doesn't have JavaFX to build?

EDIT: By installing `java-openjfx-8` from pacman, it now finds the JavaFX stuff, but there's still this going on:
```
/home/lig/projects/CCEmuX/src/main/java/net/clgd/ccemux/rendering/TerminalFont.java:38: error: cannot find symbol
                loader.getResources(FONT_RESOURCE_PATH).asIterator().forEachRemaining(u -> {
                                                       ^
  symbol:   method asIterator()
  location: interface Enumeration<URL>
/home/lig/projects/CCEmuX/src/main/java/net/clgd/ccemux/rendering/TerminalFont.java:60: error: invalid method reference
                                .flatMap(Optional::stream).sorted(comparator).findFirst()
                                         ^
  cannot find symbol
    symbol:   method stream()
    location: class Optional
/home/lig/projects/CCEmuX/src/main/java/net/clgd/ccemux/rendering/javafx/JFXRendererFactory.java:26: error: cannot find symbol
                        Platform.startup(task);
                                ^
  symbol:   method startup(FutureTask<JFXRenderer>)
  location: class Platform
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
```

Is that version of JavaFX simply too old?

EDIT 2: Those errors are caused by e28bd66e08c4cea8d32df04fe1f6a3baf93a4018. I'm guessing it's because we're using Java 9 stuff in a Java 8 project.

File: src/main/java/net/clgd/ccemux/rendering/javafx/TerminalCanvas.java [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+
+	@Override
+	public boolean isResizable() {
+		// makes sure that this element is drawn with a rigid size and not
+		// resized by parents
+		return true;
+	}
+
+	public void redraw() {
+		val g = canvas.getGraphicsContext2D();
```
Comment (Lignum) [inline src/main/java/net/clgd/ccemux/rendering/javafx/TerminalCanvas.java]: There should probably be a lock on `terminal` here, all the other renderers are doing it.

File: src/main/java/net/clgd/ccemux/rendering/javafx/JFXTerminalFont.java [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+		val reader = base.getPixelReader();
+		val writer = out.getPixelWriter();
+
+		// TODO: probably faster to use a PixelFormat
+		for (int x = 0; x < coords.width; x++) {
+			for (int y = 0; y < coords.height; y++) {
+				Color oc = reader.getColor(coords.x + x, coords.y + y);
+
+				writer.setColor(x, y, Color.color(oc.getRed() * color.getRed(), oc.getGreen() * color.getGreen(),
+						oc.getBlue() * color.getBlue(), oc.getOpacity()));
```
Comment (Lignum) [inline src/main/java/net/clgd/ccemux/rendering/javafx/JFXTerminalFont.java:60]: This again? :/ Is there no better way?

File: src/main/java/net/clgd/ccemux/rendering/javafx/JFXRenderer.java [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+			}
+		});
+	}
+
+	@Override
+	public void dispose() {
+		Platform.runLater(stage::close);
+	}
+
+	private Set<Listener> listeners = ConcurrentHashMap.newKeySet();
```
Comment (Lignum) [inline src/main/java/net/clgd/ccemux/rendering/javafx/JFXRenderer.java]: This should be `final`.

File: src/main/java/net/clgd/ccemux/plugins/builtin/JFXPlugin.java [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+	}
+
+	@Override
+	public Optional<String> getVersion() {
+		return Optional.empty();
+	}
+
+	@Override
+	public Collection<String> getAuthors() {
+		return Collections.singleton("CLGD");
```
Comment (Lignum) [inline src/main/java/net/clgd/ccemux/plugins/builtin/JFXPlugin.java:43]: This probably belongs in its own issue, but since we're in the CCEmuX organisation now, perhaps "CCEmuX Team" or similar should be the author instead?

**Comment by Lignum** [comment]
Alright, now that those issues are fixed, the last problem is:
```
/home/travis/build/CCEmuX/CCEmuX/src/main/java/net/clgd/ccemux/rendering/javafx/JFXRendererFactory.java:26: error: cannot find symbol
			Platform.startup(task);
			        ^
  symbol:   method startup(FutureTask<JFXRenderer>)
  location: class Platform
```
It seems you're supposed to use `Application.launch` in JavaFX 8.

File: src/main/java/net/clgd/ccemux/rendering/javafx/JFXRenderer.java (hunk 3 above)
Comment (dmarcuse) [reply src/main/java/net/clgd/ccemux/rendering/javafx/JFXRenderer.java]: Technically it already is because of `@Value` but I'll change it

File: src/main/java/net/clgd/ccemux/plugins/builtin/JFXPlugin.java (hunk 4 above)
Comment (dmarcuse) [reply src/main/java/net/clgd/ccemux/plugins/builtin/JFXPlugin.java:43]: Yeah, that would probably be a good idea

File: src/main/java/net/clgd/ccemux/rendering/javafx/JFXTerminalFont.java (hunk 2 above)
Comment (dmarcuse) [reply src/main/java/net/clgd/ccemux/rendering/javafx/JFXTerminalFont.java:60]: There might be using `PixelFormat` to transform the colors as they're read and read an entire buffer at a time but I haven't had the time to test it yet

**Comment by dmarcuse** [comment]
```
Exception in thread "JavaFX Application Thread" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.lang.String.charAt(String.java:658)
    at net.clgd.ccemux.rendering.javafx.ComputerPane.keyTyped(ComputerPane.java:154)
```

Pressing backspace on OSX

File: src/main/java/net/clgd/ccemux/emulation/EmulatedPalette.java [hunk 5]
```diff
@@ -4,41 +4,74 @@
...
 	public EmulatedPalette(Palette delegate) {
 		this.delegate = delegate;
 	}
 
+	public void setChanged() {
+		changed = true;
+	}
+
+	public void clearChanged() {
+		changed = false;
```
Comment (Lignum) [inline src/main/java/net/clgd/ccemux/emulation/EmulatedPalette.java]: I think a `setChanged(boolean)` would be more intuitive.

File: src/main/java/net/clgd/ccemux/rendering/awt/AWTRenderer.java [hunk 6]
```diff
@@ -289,7 +285,7 @@ private boolean allowKeyEvents() {
 
 	@Override
 	public void keyTyped(KeyEvent e) {
-		if (isPrintableChar(e.getKeyChar()) & allowKeyEvents()) {
+		if (Utils.isPrintableChar(e.getKeyChar()) & allowKeyEvents()) {
```
Comment (Lignum) [inline src/main/java/net/clgd/ccemux/rendering/awt/AWTRenderer.java]: This should be `&&`, no?

File: src/main/java/net/clgd/ccemux/rendering/javafx/ComputerPane.java [hunk 7]
```diff
@@ -0,0 +1,330 @@
...
+	 */
+	private boolean isComboInProgress() {
+		return pressedKeys.containsKey(KeyCode.CONTROL) && (pressedKeys.containsKey(KeyCode.T)
+				|| pressedKeys.containsKey(KeyCode.R) || pressedKeys.containsKey(KeyCode.S));
+	}
+
+	private void keyTyped(KeyEvent e) {
+		char c = e.getCharacter().charAt(0);
+		if (Utils.isPrintableChar(c)) {
+			computer.pressChar(e.getCharacter().charAt(0));
```
Comment (Lignum) [inline src/main/java/net/clgd/ccemux/rendering/javafx/ComputerPane.java]: This argument is just `c`.

File: src/main/java/net/clgd/ccemux/rendering/javafx/JFXRenderer.java [hunk 8]
```diff
@@ -0,0 +1,95 @@
...
+		stage.setResizable(false);
+		stage.sizeToScene();
+
+		stage.initStyle(JFXPlugin.forceUtilityDecoration.get() ? StageStyle.UTILITY : StageStyle.DECORATED);
+		stage.initModality(Modality.NONE);
+		stage.setTitle(generateTitle());
+
+		stage.getIcons().add(new Image("/img/icon.png"));
+
+		stage.setOnCloseRequest(e -> listeners.forEach(l -> l.onClosed()));
```
Comment (Lignum) [inline src/main/java/net/clgd/ccemux/rendering/javafx/JFXRenderer.java]: This can be `listeners.forEach(l::onClosed)`.

**Review by Lignum — CHANGES_REQUESTED** [review]
I have some minor nitpicks, but other than that, looks good to me. Shall I wait for you to swap out the font colouring with the `PixelFormat` thingy you talked about or shall we merge this and do that in a separate PR?

File: src/main/java/net/clgd/ccemux/emulation/EmulatedPalette.java (hunk 5 above)
Comment (dmarcuse) [reply src/main/java/net/clgd/ccemux/emulation/EmulatedPalette.java]: This is just to follow the convention used by `Terminal` but I can change it

File: src/main/java/net/clgd/ccemux/rendering/awt/AWTRenderer.java (hunk 6 above)
Comment (dmarcuse) [reply src/main/java/net/clgd/ccemux/rendering/awt/AWTRenderer.java]: Yeah, my bad

File: src/main/java/net/clgd/ccemux/rendering/javafx/ComputerPane.java (hunk 7 above)
Comment (dmarcuse) [reply src/main/java/net/clgd/ccemux/rendering/javafx/ComputerPane.java]: Derp

File: src/main/java/net/clgd/ccemux/rendering/awt/AWTRenderer.java (hunk 6 above)
Comment (dmarcuse) [reply src/main/java/net/clgd/ccemux/rendering/awt/AWTRenderer.java]: Actually technically that's the fault of whoever wrote that line, all I did was refactor `isPrintableChar`, but I'll fix it anyways

**Comment by dmarcuse** [comment]
As far as `PixelFormat` goes, I think I'll do that in a second PR (along with improving the font scaling). It doesn't seem to have a significant performance impact right now due to the caching.

**Review by Lignum — APPROVED** [review]
